### ISSUE TITLE
Excel driver is missing

### ISSUE THREAD

**Issue by amiktoha** [Grafieks-Analytics/grafieks-desktop#541]
I installed Grafieks Desktop 64. My Operaing system is Windows 10 Enterprise and Microsoft office 2016.
When I click to microsoft excel then program give mistake excel driver is missing (You don't have excel driver. Download Microsoft excel to enable it) 
![Excel mistake](https://user-images.githubusercontent.com/5108488/232248991-2d2d8df7-eb41-430e-92f8-8cdb42467445.png)

**Comment by kocharee** [comment]
Thanks for the report. Seems like you do not have the required driver.

You can follow either point 2 or 3 from the knowledge base which you can access from the below URL.
https://grafieks.freshdesk.com/support/solutions/articles/103000095563-driver-download-for-data-connector

If you have any issues then you can raise the same in the Grafieks community portal. Here is the URL.
https://community.grafieks.com/
